"""empty message

Revision ID: 10d702c98721
Revises: df6b21e08be4
Create Date: 2018-07-17 15:51:48.313915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d702c98721'
down_revision = 'df6b21e08be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apicase_info', sa.Column('assertfunction', sa.String(length=1024), nullable=True))
    op.add_column('apicase_info', sa.Column('beforefunction', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apicase_info', 'beforefunction')
    op.drop_column('apicase_info', 'assertfunction')
    # ### end Alembic commands ###
