"""empty message

Revision ID: 35295758267d
Revises: dde8b0526b39
Create Date: 2018-08-29 15:48:07.827434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35295758267d'
down_revision = 'dde8b0526b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fun_paths', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fun_paths', 'name')
    # ### end Alembic commands ###
