"""empty message

Revision ID: dde8b0526b39
Revises: 10d702c98721
Create Date: 2018-08-29 10:56:36.128899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dde8b0526b39'
down_revision = '10d702c98721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_info', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_column('api_info', 'apiname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_info', sa.Column('apiname', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('api_info', 'name')
    # ### end Alembic commands ###
