"""empty message

Revision ID: df6b21e08be4
Revises: caa1068afb74
Create Date: 2018-07-16 16:46:29.379666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6b21e08be4'
down_revision = 'caa1068afb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apicase_info', sa.Column('casename', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apicase_info', 'casename')
    # ### end Alembic commands ###
